### ISSUE TITLE
dogeify function not working for node version v14.5.0

### ISSUE THREAD

**Issue by memeToasty** [jozsefsallai/dogeify#4]
![grafik](https://user-images.githubusercontent.com/31214870/107362977-c75adb80-6ad9-11eb-8127-cd6991aa874f.png)
This is the example code, that I ran

I get this SyntaxError, that I cannot resolve:
![grafik](https://user-images.githubusercontent.com/31214870/107363102-fb360100-6ad9-11eb-9f65-c5df2b4789ec.png)

Without the await, the code obviously does not work, as it is an async function

**Comment by memeToasty** [comment]
I was just being stupid, not to define the function I wanted the module to use in, as an async one.
Example code still not working tho

**Comment by jozsefsallai** [comment]
> Example code still not working tho

is this still relevant? this works for me in runkit with node v14: https://runkit.com/embed/5csv3ec4jfkk
